import { BellEvent, DayOfWeek, MorningActivity, SystemSettings } from '../types';

export const DEFAULT_WEEKDAYS: DayOfWeek[] = ['senin', 'selasa', 'rabu', 'kamis', 'jumat'];
export const ALL_DAYS: DayOfWeek[] = ['senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu'];
export const CURRENT_SCHEDULE_REVISION = 2;

export const DEFAULT_SCHEDULES: BellEvent[] = [
  {
    id: 'pags-event-01',
    name: 'Morning Activity',
    time: '06:45',
    endTime: '07:30',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'morning',
    description: 'Kegiatan pagi sesuai jadwal harian (Upacara, Literasi/Vocab, Socratic Society, Duha & Al-Kahf)',
  },
  {
    id: 'pags-event-02',
    name: 'Mulai JP 1',
    time: '07:30',
    endTime: '08:10',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'class',
    jpCount: 1,
    description: 'Jam Pelajaran 1 (40 menit)',
  },
  {
    id: 'pags-event-jp-02',
    name: 'Pergantian ke JP 2',
    time: '08:10',
    endTime: '08:50',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'class',
    jpCount: 1,
    description: 'Jam Pelajaran 2 (40 menit)',
  },
  {
    id: 'pags-event-03',
    name: 'Istirahat',
    time: '08:50',
    endTime: '09:05',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'recess',
    description: 'Recess / Waktu Istirahat Pagi (15 Menit)',
  },
  {
    id: 'pags-event-04',
    name: 'Masuk Setelah Istirahat / Mulai JP 3',
    time: '09:05',
    endTime: '09:45',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'class',
    jpCount: 1,
    description: 'Jam Pelajaran 3 (40 menit)',
  },
  {
    id: 'pags-event-jp-04',
    name: 'Pergantian ke JP 4',
    time: '09:45',
    endTime: '10:25',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'class',
    jpCount: 1,
    description: 'Jam Pelajaran 4 (40 menit)',
  },
  {
    id: 'pags-event-indonesia-raya-mars',
    name: 'Menyanyikan Lagu Indonesia Raya & Mars PAGS',
    time: '10:00',
    endTime: '10:05',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'morning',
    description: 'Menyanyikan Lagu Kebangsaan Indonesia Raya dan Mars Praditya Adigana Global School (PAGS)',
  },
  {
    id: 'pags-event-05',
    name: 'Pergantian ke JP 5',
    time: '10:25',
    endTime: '11:05',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'class',
    jpCount: 1,
    description: 'Jam Pelajaran 5 (40 menit)',
  },
  {
    id: 'pags-event-jp-06',
    name: 'Pergantian ke JP 6',
    time: '11:05',
    endTime: '11:45',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'class',
    jpCount: 1,
    description: 'Jam Pelajaran 6 (40 menit)',
  },
  {
    id: 'pags-event-06',
    name: 'Lunch Break & Zuhur Prayer',
    time: '11:45',
    endTime: '13:00',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'ishoma',
    description: 'Ishoma (Makan Siang & Ibadah Salat Zuhur / Jumat Berjamaah)',
  },
  {
    id: 'pags-event-07',
    name: 'Mulai Pelajaran Siang / JP 7',
    time: '13:00',
    endTime: '13:40',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'class',
    jpCount: 1,
    description: 'Jam Pelajaran 7 (40 menit)',
  },
  {
    id: 'pags-event-jp-08',
    name: 'Pergantian ke JP 8',
    time: '13:40',
    endTime: '14:20',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'class',
    jpCount: 1,
    description: 'Jam Pelajaran 8 (40 menit)',
  },
  {
    id: 'pags-event-08',
    name: 'Pergantian ke JP 9',
    time: '14:20',
    endTime: '15:00',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'class',
    jpCount: 1,
    description: 'Jam Pelajaran 9 (40 menit)',
  },
  {
    id: 'pags-event-09',
    name: 'Salat Asar / Selesai Pelajaran Reguler',
    time: '15:00',
    endTime: '15:15',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'prayer',
    description: 'Selesai KBM Reguler & Ibadah Salat Asar',
  },
  {
    id: 'pags-event-10',
    name: 'Study Hour',
    time: '15:15',
    endTime: '16:00',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'study',
    description: 'Jam Wajib Belajar Terbimbing / Mentoring',
  },
  {
    id: 'pags-event-11',
    name: 'Extracurricular / School Activity',
    time: '16:00',
    endTime: '17:00',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'extracurricular',
    description: 'Kegiatan Ekstrakurikuler & Pengembangan Bakat Siswa',
  },
  {
    id: 'pags-event-12',
    name: 'Dismissal Ceremony',
    time: '17:00',
    endTime: '17:15',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'dismissal',
    description: 'Persiapan Pulang & Upacara Penutupan Hari',
  },
  {
    id: 'pags-event-13',
    name: 'Pulang',
    time: '17:15',
    endTime: undefined,
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'dismissal',
    description: 'Bel Akhir Sekolah / Waktu Kepulangan',
  },
];

export const DEFAULT_MORNING_ACTIVITIES: Record<DayOfWeek, MorningActivity> = {
  senin: {
    day: 'senin',
    title: 'FLAG CEREMONY',
    smpTitle: 'FLAG CEREMONY (Upacara Bendera)',
    smaTitle: 'FLAG CEREMONY (Upacara Bendera)',
    timeRange: '06:45 - 07:30',
    description: 'Upacara Bendera Mingguan seluruh civitas akademika',
  },
  selasa: {
    day: 'selasa',
    title: 'LITERACY & VOCABULARY',
    smpTitle: 'BOOK READING',
    smaTitle: 'DAILY VOCABS',
    timeRange: '06:45 - 07:30',
    description: 'Penguatan Literasi & Kosakata Bahasa Internasional',
  },
  rabu: {
    day: 'rabu',
    title: 'VOCABULARY & LITERACY',
    smpTitle: 'DAILY VOCABS',
    smaTitle: 'BOOK READING',
    timeRange: '06:45 - 07:30',
    description: 'Pengayaan Kosakata & Membaca Mandiri Berbasis Target',
  },
  kamis: {
    day: 'kamis',
    title: 'SOCRATIC SOCIETY',
    smpTitle: 'SOCRATIC SOCIETY (Diskusi Kritis)',
    smaTitle: 'SOCRATIC SOCIETY (Debat & Dialektika)',
    timeRange: '06:45 - 07:30',
    description: 'Forum Diskusi Berpikir Kritis & Dialektika Siswa',
  },
  jumat: {
    day: 'jumat',
    title: 'DUHA & AL-KAHF',
    smpTitle: 'SALAT DUHA & TADARUS AL-KAHF',
    smaTitle: 'SALAT DUHA & TADARUS AL-KAHF',
    timeRange: '06:45 - 07:30',
    description: 'Pembinaan Karakter Spiritual, Ibadah Duha, dan Tadarus Surat Al-Kahf',
  },
  sabtu: {
    day: 'sabtu',
    title: 'WEEKEND / NONAKTIF',
    smpTitle: 'Libur Akhir Pekan / Kegiatan Khusus',
    smaTitle: 'Libur Akhir Pekan / Kegiatan Khusus',
    timeRange: '06:45 - 07:30',
    description: 'Bel Sekolah Otomatis Nonaktif secara default',
  },
  minggu: {
    day: 'minggu',
    title: 'WEEKEND / NONAKTIF',
    smpTitle: 'Libur Akhir Pekan',
    smaTitle: 'Libur Akhir Pekan',
    timeRange: '06:45 - 07:30',
    description: 'Bel Sekolah Otomatis Nonaktif secara default',
  },
};

export const DEFAULT_SETTINGS: SystemSettings = {
  isSystemActive: false, // User explicitly clicks "AKTIFKAN SISTEM BEL" on first load
  masterVolume: 1.0,
  isMuted: false,
  weekendEnabled: false,
  autoDismissFloatingPlayerSeconds: 15,
  schoolName: 'PRADITYA ADHIGANA GLOBAL SCHOOL',
  subTitle: 'AUTOMATIC SCHOOL BELL SYSTEM',
  scheduleRevision: CURRENT_SCHEDULE_REVISION,
};

const LEGACY_DEFAULT_IDS = new Set([
  'pags-event-01',
  'pags-event-02',
  'pags-event-03',
  'pags-event-04',
  'pags-event-indonesia-raya-mars',
  'pags-event-05',
  'pags-event-06',
  'pags-event-07',
  'pags-event-08',
  'pags-event-09',
  'pags-event-10',
  'pags-event-11',
  'pags-event-12',
  'pags-event-13',
]);

const NEW_EVENT_SOURCE_IDS: Record<string, string> = {
  'pags-event-jp-02': 'pags-event-02',
  'pags-event-jp-04': 'pags-event-04',
  'pags-event-jp-06': 'pags-event-05',
  'pags-event-jp-08': 'pags-event-07',
};

const MANAGED_DEFAULT_IDS = new Set(DEFAULT_SCHEDULES.map((schedule) => schedule.id));

/**
 * Upgrade the former multi-JP blocks to one event per 40-minute JP while
 * retaining each existing event's audio, volume, enabled state, and weekdays.
 */
export function migrateSchedulesToCurrentRevision(schedules: BellEvent[]): BellEvent[] {
  const existingById = new Map(schedules.map((schedule) => [schedule.id, schedule]));

  const revisedDefaults = DEFAULT_SCHEDULES.map((defaultEvent) => {
    const sourceId = NEW_EVENT_SOURCE_IDS[defaultEvent.id] || defaultEvent.id;
    const source = existingById.get(sourceId);

    if (!source) return { ...defaultEvent, days: [...defaultEvent.days] };

    return {
      ...defaultEvent,
      days: [...source.days],
      audioId: source.audioId,
      audioName: source.audioName,
      volume: source.volume,
      enabled: source.enabled,
      notes: source.notes,
    };
  });

  const customEvents = schedules.filter(
    (schedule) => !LEGACY_DEFAULT_IDS.has(schedule.id) && !MANAGED_DEFAULT_IDS.has(schedule.id),
  );
  return [...revisedDefaults, ...customEvents].sort((a, b) => a.time.localeCompare(b.time));
}
