import { BellEvent, DayOfWeek, MorningActivity, SystemSettings } from '../types';

export const DEFAULT_WEEKDAYS: DayOfWeek[] = ['senin', 'selasa', 'rabu', 'kamis', 'jumat'];
export const ALL_DAYS: DayOfWeek[] = ['senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu'];

export const DEFAULT_SCHEDULES: BellEvent[] = [
  {
    id: 'pags-event-01',
    name: 'Morning Activity',
    time: '06:45',
    endTime: '07:30',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'morning',
    description: 'Kegiatan pagi sesuai jadwal harian (Upacara, Literasi/Vocab, Socratic Society, Duha & Al-Kahf)',
  },
  {
    id: 'pags-event-02',
    name: 'Mulai Pelajaran',
    time: '07:30',
    endTime: '08:50',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'class',
    jpCount: 2,
    description: 'Pelajaran Blok 1 (2 JP = 80 Menit)',
  },
  {
    id: 'pags-event-03',
    name: 'Istirahat',
    time: '08:50',
    endTime: '09:05',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'recess',
    description: 'Recess / Waktu Istirahat Pagi (15 Menit)',
  },
  {
    id: 'pags-event-04',
    name: 'Masuk Setelah Istirahat',
    time: '09:05',
    endTime: '10:25',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'class',
    jpCount: 2,
    description: 'Pelajaran Blok 2 (2 JP = 80 Menit)',
  },
  {
    id: 'pags-event-05',
    name: 'Pergantian Pelajaran',
    time: '10:25',
    endTime: '11:45',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'class',
    jpCount: 2,
    description: 'Pelajaran Blok 3 (2 JP = 80 Menit)',
  },
  {
    id: 'pags-event-06',
    name: 'Lunch Break & Zuhur Prayer',
    time: '11:45',
    endTime: '13:00',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'ishoma',
    description: 'Ishoma (Makan Siang & Ibadah Salat Zuhur / Jumat Berjamaah)',
  },
  {
    id: 'pags-event-07',
    name: 'Mulai Pelajaran Siang',
    time: '13:00',
    endTime: '14:20',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'class',
    jpCount: 2,
    description: 'Pelajaran Blok Siang (2 JP: 13:00-14:20 atau 3 JP: 13:00-15:00)',
  },
  {
    id: 'pags-event-08',
    name: 'Pergantian Pelajaran / 2 JP',
    time: '14:20',
    endTime: '15:00',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'class',
    description: 'Penanda pergantian untuk blok 2 JP (Kelas 3 JP tetap lanjut hingga 15:00)',
  },
  {
    id: 'pags-event-09',
    name: 'Salat Asar / Selesai Pelajaran Reguler',
    time: '15:00',
    endTime: '15:15',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'prayer',
    description: 'Selesai KBM Reguler & Ibadah Salat Asar',
  },
  {
    id: 'pags-event-10',
    name: 'Study Hour',
    time: '15:15',
    endTime: '16:00',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'study',
    description: 'Jam Wajib Belajar Terbimbing / Mentoring',
  },
  {
    id: 'pags-event-11',
    name: 'Extracurricular / School Activity',
    time: '16:00',
    endTime: '17:00',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'extracurricular',
    description: 'Kegiatan Ekstrakurikuler & Pengembangan Bakat Siswa',
  },
  {
    id: 'pags-event-12',
    name: 'Dismissal Ceremony',
    time: '17:00',
    endTime: '17:15',
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'dismissal',
    description: 'Persiapan Pulang & Upacara Penutupan Hari',
  },
  {
    id: 'pags-event-13',
    name: 'Pulang',
    time: '17:15',
    endTime: undefined,
    days: [...DEFAULT_WEEKDAYS],
    audioId: null,
    audioName: '',
    volume: 1.0,
    enabled: true,
    category: 'dismissal',
    description: 'Bel Akhir Sekolah / Waktu Kepulangan',
  },
];

export const DEFAULT_MORNING_ACTIVITIES: Record<DayOfWeek, MorningActivity> = {
  senin: {
    day: 'senin',
    title: 'FLAG CEREMONY',
    smpTitle: 'FLAG CEREMONY (Upacara Bendera)',
    smaTitle: 'FLAG CEREMONY (Upacara Bendera)',
    timeRange: '06:45 - 07:30',
    description: 'Upacara Bendera Mingguan seluruh civitas akademika',
  },
  selasa: {
    day: 'selasa',
    title: 'LITERACY & VOCABULARY',
    smpTitle: 'BOOK READING',
    smaTitle: 'DAILY VOCABS',
    timeRange: '06:45 - 07:30',
    description: 'Penguatan Literasi & Kosakata Bahasa Internasional',
  },
  rabu: {
    day: 'rabu',
    title: 'VOCABULARY & LITERACY',
    smpTitle: 'DAILY VOCABS',
    smaTitle: 'BOOK READING',
    timeRange: '06:45 - 07:30',
    description: 'Pengayaan Kosakata & Membaca Mandiri Berbasis Target',
  },
  kamis: {
    day: 'kamis',
    title: 'SOCRATIC SOCIETY',
    smpTitle: 'SOCRATIC SOCIETY (Diskusi Kritis)',
    smaTitle: 'SOCRATIC SOCIETY (Debat & Dialektika)',
    timeRange: '06:45 - 07:30',
    description: 'Forum Diskusi Berpikir Kritis & Dialektika Siswa',
  },
  jumat: {
    day: 'jumat',
    title: 'DUHA & AL-KAHF',
    smpTitle: 'SALAT DUHA & TADARUS AL-KAHF',
    smaTitle: 'SALAT DUHA & TADARUS AL-KAHF',
    timeRange: '06:45 - 07:30',
    description: 'Pembinaan Karakter Spiritual, Ibadah Duha, dan Tadarus Surat Al-Kahf',
  },
  sabtu: {
    day: 'sabtu',
    title: 'WEEKEND / NONAKTIF',
    smpTitle: 'Libur Akhir Pekan / Kegiatan Khusus',
    smaTitle: 'Libur Akhir Pekan / Kegiatan Khusus',
    timeRange: '06:45 - 07:30',
    description: 'Bel Sekolah Otomatis Nonaktif secara default',
  },
  minggu: {
    day: 'minggu',
    title: 'WEEKEND / NONAKTIF',
    smpTitle: 'Libur Akhir Pekan',
    smaTitle: 'Libur Akhir Pekan',
    timeRange: '06:45 - 07:30',
    description: 'Bel Sekolah Otomatis Nonaktif secara default',
  },
};

export const DEFAULT_SETTINGS: SystemSettings = {
  isSystemActive: false, // User explicitly clicks "AKTIFKAN SISTEM BEL" on first load
  masterVolume: 1.0,
  isMuted: false,
  weekendEnabled: false,
  autoDismissFloatingPlayerSeconds: 15,
  schoolName: 'PRADITYA ADHIGANA GLOBAL SCHOOL',
  subTitle: 'AUTOMATIC SCHOOL BELL SYSTEM',
};
